### PR TITLE
[SECURITY-657] Add test for the XXE correction

### PR DESCRIPTION
**Pull request by Wadeck**
- add test for non-regression on XXE

[SECURITY-657](https://issues.jenkins-ci.org/browse/SECURITY-657)

@reviewbybees @daniel-beck @uhafner

### CODE REVIEW

**Comment by uhafner** [comment]
Thanks! I let this PR open until all SECURITY-657 changes are merged into the 3.0 branch of my plugins.

**Comment by Wadeck** [comment]
@reviewbybees done (actually not necessarily as maintainer approved it)

**Comment by NicoleG25** [comment]
Hi, has this issue been fixed then? :) thanks.

**Comment by uhafner** [comment]
Yes. The plugin has been replaced by the warnings plugin anyway.

**Comment by uhafner** [comment]
PR is not required anymore.

**Pull request closed without merging**
